def add_user_source_totals():
    manchat_total = 0
    not_manchat_total = 0

    manchat = {
        "Jason": 157985,
        "Chris": 111841,
        "Kyle": 106183,
        "James": 101031,
        "Nickolus": 56445,
        "Aaron": 14377,
        "Andrew": 51061,
        "Ken": 220,
        "shamuhooka": 4,
        "lostinataraxia": 7,
        "Neil": 3,
        "steve": 2,
    }

    not_manchat = {
        "Alex": 257,
        "Erik": 1201,
        "Cunningham": 353,
        "brittanybishopmail@gmail.com": 204,
        "Madeline": 126,
        "Marguerite": 12,
        "reply-116352009742563139397@profiles.google.com": 4,
        "reply-118212305404270876486@profiles.google.com": 1,
        "Yukie": 3,
        "reply-113733010490751143876@profiles.google.com": 1,
        "Gabriel": 32,
        "Koshin": 358,
        "Jorge": 8,
        "Clark": 1,
        "unknown": 1,
        "Dan": 1,
        "Brian": 4,
        "Karen": 57,
        "Jas": 2,
        "amy": 98,
        "Asha": 40,
        "sammdaniel.sd@gmail.com": 126,
        "shayne": 1,
        "shawn": 122,
        "Samaria": 67,
        "samaria@thesproutingimage.com": 29,
        "erica": 3,
        "Nick": 3,
        "Karin": 126,
        "Ashley": 3,
        "Mariana": 51,
        "srfgrlsara": 15,
        "Larry": 2,
        "larrymarkovitz@gmail.com": 3,
        "aim": 1,
        "mia.c.flores@gmail.com": 8,
        "marisawilshire": 36,
        "pchinique@gmail.com": 7,
        "hoboskate123": 18,
        "Patrick": 10,
        "talkwithdan": 36,
        "bdmoreland18@gmail.com": 33,
        "Jeanna": 61,
        "Taryn": 2,
        "jean": 3,
        "sexyskinnywomen": 1,
        "Laurel": 2,
        "9rrats@gmail.com": 53,
        "onwhitevelour": 60,
        "Steven": 1,
        "Heather": 21,
        "Daniel": 13,
        "sunkistme04": 52,
        "aflightanacrash": 9,
        "chrissyann9": 21,
        "Nik": 9,
        "Hasan": 4,
        "Evan": 3,
        "Benjamin": 2,
        "Ryan": 9,
        "Tres": 6,
        "jesssiffer": 8,
        "prestigefatigue": 152,
        "jesss2theresq": 8,
        "rxisforlove": 5,
        "food0000": 5,
        "roberthenrylowe": 38,
        "mecfu": 3,
        "happie4life20": 3,
        "heartxxofxxglass": 1,
        "hitrayaledi": 7,
        "huesos": 17,
        "evan.montes@gmail.com": 7,
        "ryanblueshoes@gmail.com": 1,
        "gigijicoma584": 10,
        "ryanblue78": 84,
        "Caryn": 4,
        "MarisaWilshire@gmail.com": 9,
        "doodeykins": 5,
        "gnarink@gmail.com": 8,
        "boxingclever7": 6,
        "nismoboost3": 3,
        "snelegisc@gmail.com": 6,
        "libertygerbil": 41,
        "shayne.sanderson@gmail.com": 9,
        "lactatingbeavers": 2,
        "Marina": 4,
        "mylipsyourhips": 23,
        "notspenceronaim": 17,
        "invaderzim1114": 8,
        "h20ispoison": 2,
        "Mariana": 1,
        "Shawn": 1,
        "cedartaylor@gmail.com": 15,
        "kasiabrucker@gmail.com": 2,
        "idanceondedminds": 5,
        "tarynpopp@gmail.com": 209,
        "chicken041": 15,
        "loovemetwotimes": 4,
        "atotheyano": 2,
        "macbo3000": 8,
        "rachtilldeath": 4,
        "margotttenenbaum": 2,
        "Juan": 1,
        "taryn": 26,
        "krayola228": 6,
        "Frank": 3,
        "huesos.sd@gmail.com": 1,
        "flygirlx00": 1,
        "Nick": 4,
        "intensesagacity": 6,
        "waterdrop123": 3,
        "lovelyeyes1983": 3,
        "Jeanna": 4,
        "thepkstyles": 3,
        "lauratheposer": 2,
        "firelikesunrise": 6,
        "shyeyez478": 1,
        "Nicole": 23,
        "Jen": 15,
        "Michael": 1,
        "marisawilshire@gmail.com": 3,
        "xxitwounds": 1,
        "Nicole": 1,
        "Matt": 5,
        "zipmazambi": 1,
        "eunaotenhoideia": 1,
        "jenruhman@gmail.com": 1,
        "matthewbrennan@gmail.com": 1,
        "szkutch": 4,
        "virtuosoissolo": 1,
        "hmschenher@gmail.com": 2,
        "taryn": 1,
        "xstateofnaturex": 1,
        "maggotpriest": 1,
        "mynameischelseaj": 1,
        "jipaipai@gmail.com": 1,
    }

    for chat in manchat:
        manchat_total += manchat[chat]

    for chat in not_manchat:
        not_manchat_total += not_manchat[chat]

    print(manchat_total)
    print(not_manchat_total)

